#!/usr/bin/env node
// Geocodes events.venue_name into events.lat/lng (migration 0003) so the
// themed map (apps/web/public/bolivamos/city-scene.js) can place real event
// markers. Same Nominatim pipeline as packages/db/scripts/geocode-places.mjs
// — see that file for the rate-limit/verification rationale. Deduped by
// venue_name first (45 distinct venues across 59 events as of 2026-08-24)
// so shared venues (e.g. two shows at the same stadium) cost one request.
//
// Reads events straight from remote D1 via `wrangler d1 execute --json`
// (events live in the app's live database, not a static JSON file like
// places.json) and writes an UPDATE statement per event to
// packages/db/seeds/events.sql — apply with:
//   wrangler d1 execute bolivamos-db --remote --file=packages/db/seeds/events.sql
//
// Run: node packages/db/scripts/geocode-events.mjs

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SEEDS_DIR = path.join(__dirname, "../seeds");
const CHECKPOINT_PATH = path.join(SEEDS_DIR, "events-checkpoint.json");
const SQL_OUT_PATH = path.join(SEEDS_DIR, "events.sql");
const WEB_DIR = path.join(__dirname, "../../../apps/web");

const NOMINATIM_URL = "https://nominatim.openstreetmap.org/search";
const USER_AGENT = "BoliVamos-ThemedMaps/1.0 (+https://bolivamos.app; contact: hudson@tektone.com.br)";
const REQUEST_DELAY_MS = 1100;
const CITY_SUFFIX = "Santa Cruz de la Sierra, Bolivia";

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function geocode(query) {
  const url = new URL(NOMINATIM_URL);
  url.searchParams.set("q", query);
  url.searchParams.set("format", "jsonv2");
  url.searchParams.set("limit", "1");
  url.searchParams.set("accept-language", "es");
  const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
  if (!res.ok) throw new Error(`Nominatim ${res.status} for "${query}"`);
  const results = await res.json();
  if (!results.length) return null;
  const r = results[0];
  return { lat: parseFloat(r.lat), lng: parseFloat(r.lon), displayName: r.display_name };
}

function sqlString(v) {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
}

async function main() {
  console.log("Fetching events from remote D1...");
  const raw = execSync(
    `npx wrangler d1 execute bolivamos-db --remote --command "SELECT id, venue_name FROM events WHERE venue_name IS NOT NULL" --json`,
    { cwd: WEB_DIR, env: { ...process.env, CLOUDFLARE_ACCOUNT_ID: "cb27e1a67198789eb42d11ab90737652" }, maxBuffer: 10 * 1024 * 1024 },
  );
  const events = JSON.parse(raw.toString())[0].results;
  console.log(`${events.length} events with a venue name.`);

  const uniqueVenues = [...new Set(events.map((e) => e.venue_name))];
  console.log(`${uniqueVenues.length} distinct venues to geocode.`);

  let checkpoint = { results: {} };
  if (existsSync(CHECKPOINT_PATH)) {
    checkpoint = JSON.parse(readFileSync(CHECKPOINT_PATH, "utf8"));
    console.log(`Resuming: ${Object.keys(checkpoint.results).length} venues already geocoded.`);
  }

  let count = 0;
  for (const venue of uniqueVenues) {
    if (checkpoint.results[venue]) continue;
    count++;
    try {
      const g = await geocode(`${venue}, ${CITY_SUFFIX}`);
      if (!g) {
        checkpoint.results[venue] = { lat: null, lng: null, verified: false, reason: "no-match" };
      } else {
        checkpoint.results[venue] = {
          lat: g.lat,
          lng: g.lng,
          verified: /Bolivia/i.test(g.displayName ?? ""),
          displayName: g.displayName,
        };
      }
    } catch (err) {
      console.warn(`  ! ${venue}: ${err.message}`);
      checkpoint.results[venue] = { lat: null, lng: null, verified: false, reason: String(err.message) };
    }
    if (count % 10 === 0) {
      writeFileSync(CHECKPOINT_PATH, JSON.stringify(checkpoint, null, 2));
      console.log(`  ...${count}/${uniqueVenues.length - Object.keys(checkpoint.results).length + count} geocoded this run.`);
    }
    await sleep(REQUEST_DELAY_MS);
  }
  writeFileSync(CHECKPOINT_PATH, JSON.stringify(checkpoint, null, 2));

  const sqlLines = ["-- Generated by packages/db/scripts/geocode-events.mjs — do not hand-edit."];
  let verifiedEvents = 0;
  for (const event of events) {
    const g = checkpoint.results[event.venue_name];
    if (!g || !g.verified) continue;
    verifiedEvents++;
    sqlLines.push(`UPDATE events SET lat = ${sqlString(g.lat)}, lng = ${sqlString(g.lng)} WHERE id = ${sqlString(event.id)};`);
  }
  writeFileSync(SQL_OUT_PATH, sqlLines.join("\n") + "\n");
  console.log(`\nWrote ${SQL_OUT_PATH}`);
  console.log(`${verifiedEvents}/${events.length} events geocoded (${uniqueVenues.length} distinct venues).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
